---

name: Check

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v3

      - name: Run test
        run: |
          cd /home/runner/work/devops-demo-service/devops_demo && python3 manage.py test
          
      - name: Build and run container
        run: |
          docker-compose up -d --build
