name: Build Docker Container after Django Test

on:
  push:
    branches: [main]

jobs:
  checks_path:
    uses: SquareSq/devops-demo-service/.github/workflows/check.yml@main
  container_builder:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build container image
        run: |
          docker build \
          -t your-username/your-image-name:${GITHUB_SHA::7} \
          -t your-username/your-image-name:latest \
          .
